# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1986b07905dfb71ea7ae0863fd072e7356ea456a05372e6e268e0fee7d91bbab99d197fe57bd0430aea03d7f6d5040bda7d64050f02294cd7a4a51edcaf68ecd

test:
  secret_key_base: d69f865a66b977b1ddc816fafac92e84464f2bcb4aa7158f6088ac73f17c28736cc249ab3f69ab171f02083e9e42cd3e69c80930ead0a3ddf8b566a6d3d381f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
